--DDL - Data Defination Language

--criar o banco de dados
CREATE DATABASE [Event+_Tarde];

USE [Event+_Tarde];

--criar as tabelas
CREATE TABLE TiposDeUsuario
(
	IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	TituloTipoUsuario VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE TiposDeEvento
(
	IdTipoDeEvento UNIQUEIDENTIFIER PRIMARY KEY,
	TituloTipoDeEvento VARCHAR(50) UNIQUE NOT NULL
);

--adiciona uma chave para uma coluna já criada
-- ALTER TABLE TiposDeEvento ADD UNIQUE (TituloTipoDeEvento);

CREATE TABLE Instituicao
(
	IdInstituicao UNIQUEIDENTIFIER PRIMARY KEY,
	NomeFantasia VARCHAR(200) NOT NULL,
	CNPJ CHAR(14) NOT NULL UNIQUE,
	Endereco VARCHAR(200) NOT NULL 
);

CREATE TABLE Usuario
(
	IdUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TiposDeUsuario(IdTipoUsuario) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL UNIQUE,
	Senha VARCHAR(60) NOT NULL
);

CREATE TABLE Evento
(
	IdEvento UNIQUEIDENTIFIER PRIMARY KEY,
	IdTipoDeEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TiposDeEvento(IdTipoDeEvento) NOT NULL,
	IdInstituicao UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Instituicao(IdInstituicao) NOT NULL,
	Nome VARCHAR(200) NOT NULL,
	Descricao VARCHAR(500) NOT NULL,
	[Data] DATE NOT NULL,
	Hora TIME NOT NULL
);

CREATE TABLE PresencasEvento
(
	IdPresencasEvento INT PRIMARY KEY IDENTITY,
	IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IdEvento) NOT NULL,
	--Valor padrão - DEFAULT(0)
	SituacaoPresenca BIT
);

CREATE TABLE ComentarioEvento
(
	IdComentarioEvento UNIQUEIDENTIFIER PRIMARY KEY,
	IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IdEvento) NOT NULL,
	Titulo VARCHAR(50) NOT NULL,
	Descricao VARCHAR(500) NOT NULL,
	[Data] DATE NOT NULL,
	ComentarioExibido BIT DEFAULT(0)
);