CREATE DATABASE Exercicio_1_2;

USE Exercicio_1_2;

CREATE TABLE Cliente(
	IdCliente INT PRIMARY KEY IDENTITY,
	NomeCliente VARCHAR(50) NOT NULL,
	CpfCliente CHAR(11) NOT NULL UNIQUE
);

CREATE TABLE Locadora(
	IdLocadora INT PRIMARY KEY IDENTITY,
	NomeLocadora VARCHAR(30) NOT NULL
);

CREATE TABLE Marca(
	IdMarca INT PRIMARY KEY IDENTITY,
	NomeMarca VARCHAR(15) NOT NULL
);

CREATE TABLE Modelo(
	IdModelo INT PRIMARY KEY IDENTITY,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL,
	NomeModelo VARCHAR(15) NOT NULL,
	AnoModelo CHAR(4) NOT NULL
);

CREATE TABLE Veiculo(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdLocadora INT FOREIGN KEY REFERENCES Locadora(IdLocadora) NOT NULL,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL,
	PlacaVeiculo VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE Aluguel(
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo) NOT NULL,
	DataInicioAluguel DATETIME NOT NULL, 
	DataFinalAluguel DATETIME NOT NULL, 
	ValorAluguel MONEY NOT NULL
);

SELECT * FROM Cliente;
SELECT * FROM Locadora;
SELECT * FROM Modelo;
SELECT * FROM Marca;
SELECT * FROM Veiculo;
SELECT * FROM Aluguel;